set_pixel:
  description: 'Sets pixel value.'
  fields:
    red:
      description: 'Sets value for the color red.'
      example: 0
    green:
      description: 'Sets value for the color red.'
      example: 255
    blue:
      description: 'Sets value for the color red.'
      example: 0
    from:
      description: 'Define start pixel.'
      example: 10
    to:
      description: 'Define start pixel.'
      example: 100